"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 25;
let altura = 1.82;
const nacionalidade = "Brasileira";
const colegas = ["Gustavo", "Pedro", "Paulo"];
const tecnoclogias = ["html", "css", "js"];
const notas = [7, 8, 5, 2];
notas.forEach((number) => console.log(number));
